#!/usr/bin/env bash
# Bash script that will display information about subdomains.


display_info() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        info=$(dig +short $sub.$domain | awk '{print $1}')
        record_type=$(dig $sub.$domain | grep -A1 'ANSWER SECTION' | \
		awk '{if (NR==2) print $4}')
        echo "The subdomain $sub is a $record_type record and points to $info"
    done
}

# Check if the correct number of arguments is provided
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain=$1
subdomain=$2

# Call the function with the provided arguments
display_info $domain $subdomain
