#!/usr/bin/env bash
# Install nginx web server.

# Update package list
apt-get update

# Install Nginx
apt-get install -y nginx

# Create document root directory
mkdir -p /var/www/html

# Create index.html with "Hello World!" content
echo "Hello World!" | tee /var/www/html/index.html > /dev/null

# Nginx configuration with redirection
create_nginx_config() {
    echo "server {
        listen 80;
        server_name localhost;

        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        location / {
            root /var/www/html;
            index index.html;
        }
    }" | tee /etc/nginx/sites-available/default > /dev/null
}
create_nginx_config

# Restart Nginx
service nginx restart
