#!/usr/bin/env bash

# Update the package repository
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Function to modify HAProxy frontend and backend sections
modify_haproxy_config() {
    local haproxy_conf="/etc/haproxy/haproxy.cfg"

    # Create a backup by copying the original file
    sudo cp "$haproxy_conf" "$haproxy_conf.bak"

    # Modify the frontend and backend sections
    echo "
frontend main
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 3.85.148.189:80 check
    server web-02 54.87.195.116:80 check
" | sudo tee -a "$haproxy_conf" > /dev/null
}

# Call the function to modify the HAProxy configuration
modify_haproxy_config

# HAProxy service restart
sudo service haproxy restart
