#!/usr/bin/env bash

# MySQL credentials
MYSQL_USER="root"
MYSQL_PASSWORD="$1"

# MySQL user details
DB_USER="holberton_user"
DB_PASSWORD="projectcorrection280hbt"
DB_HOST="localhost"

# Function to create MySQL user
create_mysql_user() {
    mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "CREATE USER '$DB_USER'@'$DB_HOST' IDENTIFIED BY '$DB_PASSWORD';" \
    && mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "GRANT ALL PRIVILEGES ON *.* TO '$DB_USER'@'$DB_HOST';" \
    && mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "FLUSH PRIVILEGES;"
}

# Create MySQL user on web-01
echo "Creating MySQL user on web-01..."
ssh -i ~/.ssh/school ubuntu@web-01.botlhaledev.tech "$(declare -f create_mysql_user); create_mysql_user" </dev/null
echo "MySQL user created on web-01."

# Create MySQL user on web-02
echo "Creating MySQL user on web-02..."
ssh -i ~/.ssh/school ubuntu@web-02.botlhaledev.tech "$(declare -f create_mysql_user); create_mysql_user" </dev/null
echo "MySQL user created on web-02."
