#!/usr/bin/env bash
# 101-manage_my_process Bash Script.

# Check if the argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi

# Check if the script is run with superuser privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root (sudo)."
    exit 1
fi

# Define the path to the manage_my_process script
MANAGE_SCRIPT="./manage_my_process"

case "$1" in
    "start")
        # Start manage_my_process
        $MANAGE_SCRIPT start
        ;;
    "stop")
        # Stop manage_my_process
        $MANAGE_SCRIPT stop
        ;;
    "restart")
        # Restart manage_my_process
        $MANAGE_SCRIPT restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
