#!/usr/bin/env bash
# Bash script that manages my_process process.

PIDFILE="/var/run/my_process.pid"

start_my_process() {
    if [ -f "$PIDFILE" ]; then
        echo "manage_my_process is already running. PID: $(cat "$PIDFILE")"
        return 1
    fi

    ./my_process.sh &
    echo $! > "$PIDFILE"
    echo "manage_my_process started"
}

stop_my_process() {
    if [ -f "$PIDFILE" ]; then
        PID=$(cat "$PIDFILE")
        kill "$PID"
        rm -f "$PIDFILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart_my_process() {
    stop_my_process
    start_my_process
    echo "manage_my_process restarted"
}

case "$1" in
    "start")
        start_my_process
        ;;
    "stop")
        stop_my_process
        ;;
    "restart")
        restart_my_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
