#!/usr/bin/env bash
# 4 bad luck, 8 is your chance.

iter=0
while [ $iter -lt 10 ]
do
    if [ $iter -eq 3 ]
    then
        echo "bad luck"
    elif [ $iter -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( iter++ ))
done
