#!/usr/bin/env bash
# Configure Nginx to run as the "nginx" user on port 8080

# Stop processes using port 8080
fuser -k 8080/tcp

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

service nginx start
